name: Terraform Deployment

on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted  # Target the specific Azure VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize Terraform
        run: |
          terraform init \
          -backend-config="resource_group_name=Guild-COS-Development" \
          -backend-config="storage_account_name=costfstatestorageaccount" \
          -backend-config="container_name=tfstate-backend" \
          -backend-config="key=terraform.tfstate"

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
